In [1]:
import numpy as np
import pandas as pd


In [2]:
with open("nba_2013.csv", 'r') as csvfile:
    nba = pd.read_csv(csvfile)

In [3]:
nba.head()

player pos  age bref_team_id   g  gs    mp   fg   fga    fg.  \
0     Quincy Acy  SF   23          TOT  63   0   847   66   141  0.468   
1   Steven Adams   C   20          OKC  81  20  1197   93   185  0.503   
2    Jeff Adrien  PF   27          TOT  53  12   961  143   275  0.520   
3  Arron Afflalo  SG   28          ORL  73  73  2552  464  1011  0.459   
4  Alexis Ajinca   C   25          NOP  56  30   951  136   249  0.546   

      ...      drb  trb  ast  stl  blk  tov   pf   pts     season  season_end  
0     ...      144  216   28   23   26   30  122   171  2013-2014        2013  
1     ...      190  332   43   40   57   71  203   265  2013-2014        2013  
2     ...      204  306   38   24   36   39  108   362  2013-2014        2013  
3     ...      230  262  248   35    3  146  136  1330  2013-2014        2013  
4     ...      183  277   40   23   46   63  187   328  2013-2014        2013  

[5 rows x 31 columns]

In [5]:
nba.shape

(481, 31)

In [10]:
dist_cols = ['age', 'g', 'gs', 'mp', 'fg', 'fga', 'fg.', 'x3p', 'x3pa', 'x3p.', 'x2p', 'x2pa', 'x2p.', 'efg.', 'ft', 'fta', 'ft.', 'orb', 'drb', 'trb', 'ast', 'stl', 'blk', 'tov', 'pf', 'pts']

In [11]:
nba_new = nba[dist_cols]

In [12]:
nba_new.head()

age   g  gs    mp   fg   fga    fg.  x3p  x3pa      x3p.  ...     ft.  orb  \
0   23  63   0   847   66   141  0.468    4    15  0.266667  ...   0.660   72   
1   20  81  20  1197   93   185  0.503    0     0       NaN  ...   0.581  142   
2   27  53  12   961  143   275  0.520    0     0       NaN  ...   0.639  102   
3   28  73  73  2552  464  1011  0.459  128   300  0.426667  ...   0.815   32   
4   25  56  30   951  136   249  0.546    0     1  0.000000  ...   0.836   94   

   drb  trb  ast  stl  blk  tov   pf   pts  
0  144  216   28   23   26   30  122   171  
1  190  332   43   40   57   71  203   265  
2  204  306   38   24   36   39  108   362  
3  230  262  248   35    3  146  136  1330  
4  183  277   40   23   46   63  187   328  

[5 rows x 26 columns]

In [13]:
nba_new.shape

(481, 26)

In [24]:
nba_new.isnull().sum()

age     0
g       0
gs      0
mp      0
fg      0
fga     0
fg.     2
x3p     0
x3pa    0
x3p.    0
x2p     0
x2pa    0
x2p.    3
efg.    2
ft      0
fta     0
ft.     0
orb     0
drb     0
trb     0
ast     0
stl     0
blk     0
tov     0
pf      0
pts     0
dtype: int64

In [19]:
nba_new['x3p.'] = nba_new['x3p.'].fillna(0)

C:\Users\siddam\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [23]:
nba_new['ft.'] = nba_new['ft.'].fillna(1.0)

C:\Users\siddam\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [26]:
nba_new['fg.'] = nba_new['fg.'].fillna(0)

C:\Users\siddam\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [28]:
nba_new['efg.'] = nba_new['efg.'].fillna(0.5)

C:\Users\siddam\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [31]:
nba_new['x2p.'] =nba_new['x2p.'].fillna(0.4744)

C:\Users\siddam\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [32]:
nba_new.isnull().sum()

age     0
g       0
gs      0
mp      0
fg      0
fga     0
fg.     0
x3p     0
x3pa    0
x3p.    0
x2p     0
x2pa    0
x2p.    0
efg.    0
ft      0
fta     0
ft.     0
orb     0
drb     0
trb     0
ast     0
stl     0
blk     0
tov     0
pf      0
pts     0
dtype: int64

In [33]:
nba_normal = (nba_new - nba_new.mean()) / nba_new.std()

In [34]:
nba_normal.head()

age         g        gs        mp        fg       fga       fg.  \
0 -0.835906  0.384886 -0.862207 -0.435088 -0.738401 -0.768505  0.325957   
1 -1.550487  1.095711 -0.187863 -0.045011 -0.581271 -0.649215  0.667749   
2  0.116868 -0.010016 -0.457600 -0.308035 -0.290291 -0.405214  0.833763   
3  0.355062  0.779789  1.599148  1.465144  1.577804  1.590172  0.238067   
4 -0.359519  0.108454  0.149309 -0.319180 -0.331028 -0.475703  1.087666   

        x3p      x3pa      x3p.    ...          ft.       orb       drb  \
0 -0.700282 -0.716608  0.120520    ...    -0.444696  0.260690 -0.129462   
1 -0.778936 -0.829601 -1.390497    ...    -0.919693  1.387883  0.187020   
2 -0.778936 -0.829601 -1.390497    ...    -0.570961  0.743773  0.283340   
3  1.737992  1.430256  1.027130    ...     0.487260 -0.383420  0.462221   
4 -0.778936 -0.822068 -1.390497    ...     0.613525  0.614951  0.138859   

        trb       ast       stl       blk       tov        pf       pts  
0 -0.013116 -0.645220 -0.468056  0.061410 -0.667650  0.226515 -0.734621  
1  0.565852 -0.530733  0.020680  1.065446 -0.013760  1.363938 -0.534801  
2  0.436083 -0.568895 -0.439307  0.385292 -0.524113  0.029924 -0.328603  
3  0.216475  1.033919 -0.123066 -0.683520  1.182380  0.423107  1.729123  
4  0.291341 -0.553630 -0.468056  0.709175 -0.141348  1.139262 -0.400878  

[5 rows x 26 columns]

In [38]:

# The columns that we will be making predictions with.
x_col = ['age', 'g', 'gs', 'mp', 'fg', 'fga', 'fg.', 'x3p', 'x3pa', 'x3p.', 'x2p', 'x2pa', 'x2p.', 'efg.', 'ft', 'fta', 'ft.', 'orb', 'drb', 'trb', 'ast', 'stl', 'blk', 'tov', 'pf']
# The column that we want to predict.
y_col = ["pts"]

In [54]:
X = nba_normal[x_col]
Y = nba_normal[y_col]

In [55]:
X.shape

(481, 25)

In [56]:
Y.shape

(481, 1)

In [80]:
x_val = X.iloc[99:101, ].values
x_val

array([[-0.12132523,  0.77978861,  1.59914799,  1.3470063 ,  1.57198459,
         1.64168365,  0.15017765,  1.28573146,  1.36246074,  0.6540489 ,
         1.39062228,  1.44358971,  0.16754115,  0.19293388,  1.29060592,
         1.1837613 ,  0.48725966, -0.2384948 ,  0.06317902, -0.02808922,
         2.5069816 ,  2.0331235 , -0.35963767,  1.24617397,  0.49331818],
       [ 0.59325559, -0.48389914, -0.86220665, -1.08373041, -0.80241666,
        -0.83357171,  0.34548778, -0.13004075, -0.23450524,  0.97644389,
        -0.89162731, -0.93934923,  1.07521348,  1.31017173, -0.7833279 ,
        -0.81257157, -0.12001488, -0.78598832, -0.94818599, -0.9314789 ,
        -0.72154406, -1.04303969, -0.55396725, -0.92282657, -0.95303421]])

In [83]:
y_val = Y.iloc[99:101, ].values
y_val

array([[ 1.57181748],
       [-0.77288465]])

In [60]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X.values, Y.values, test_size=0.2, random_state = 0)


In [61]:
y_train.shape

(384, 1)

In [62]:
from sklearn.neighbors import KNeighborsRegressor

In [63]:
knn = KNeighborsRegressor(n_neighbors=5)

In [64]:
knn.fit(x_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=5, p=2,
          weights='uniform')

In [65]:
y_pred = knn.predict(x_test)

In [67]:
from sklearn.metrics import accuracy_score, mean_squared_error

score = mean_squared_error(y_test, y_pred)
score

0.029450486197005018

In [81]:
y_val_pred = knn.predict(x_val)

In [82]:
y_val_pred

array([[ 1.78396731],
       [-0.7809625 ]])